# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :code_sign_appstore do
    # 사이닝 인증서 및 프로파일 로드
    match(
      git_url: ENV['MATCH_APPLE_AUTH_GIT_REPO_URL'],
      storage_mode: 'git',
      type: 'appstore',
      app_identifier: ENV['BILLETS_APP_APPLE_BUNDLE_ID'],
      readonly: true,
      # keychain_name: ENV['MATCH_KEYCHAIN_NAME'],
      # keychain_password: ENV['MATCH_KEYCHAIN_PASSWORD'],
      verbose: true
    )
  end

  lane :beta do
    # add actions here: https://docs.fastlane.tools/actions
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      key_filepath: ENV['APP_STORE_CONNECT_API_KEY_FILEPATH'],
      duration: 1200,
      in_house: false
    )
    code_sign_appstore()
    increment_build_number(
      build_number: latest_testflight_build_number(
        api_key: api_key,
        app_identifier: ENV['BILLETS_APP_APPLE_BUNDLE_ID']
      ) + 1,
      xcodeproj: "FstvlLifeApp.xcodeproj"
    )
    build_app(
      scheme: "FstvlLifeApp",
      workspace: "FstvlLifeApp.xcworkspace",
      configuration: "Staging"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end

  lane :prod do
    # add actions here: https://docs.fastlane.tools/actions
    api_key = app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      key_filepath: ENV['APP_STORE_CONNECT_API_KEY_FILEPATH'],
      duration: 1200,
      in_house: false
    )
    code_sign_appstore()
    increment_build_number(
      build_number: latest_testflight_build_number(
        api_key: api_key,
        app_identifier: ENV['BILLETS_APP_APPLE_BUNDLE_ID']
      ) + 1,
      xcodeproj: "FstvlLifeApp.xcodeproj"
    )
    build_app(
      scheme: "FstvlLifeApp",
      workspace: "FstvlLifeApp.xcworkspace",
      configuration: "Release"
    )
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
