FROM node:20.16.0-alpine AS builder
WORKDIR /surfers-root
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=${GITHUB_TOKEN}

RUN corepack enable

COPY package.json ./package.json
COPY yarn.lock ./yarn.lock
COPY .yarnrc.yml ./.yarnrc.yml
COPY ./tsconfig.base.json ./tsconfig.base.json
COPY ./packages ./packages
COPY ./apps/coldsurf-io ./apps/coldsurf-io

WORKDIR /surfers-root/apps/coldsurf-io
RUN yarn install
RUN yarn workspace @coldsurfers/coldsurf-io build

EXPOSE 4001
CMD ["yarn", "start"]
