name: 'Docker Compose build and push action'
description: 'docker compose build and push to ecr'
inputs:
  docker_compose_service:
    description: 'docker compose service name to build and push to ecr'
    required: true
  aws_ecr_repository:
    description: 'AWS ecr repository address'
    required: true
  github_token:
    description: 'github token for ci'
    required: true
  docker_image_tag:
    description: 'docker image tag'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Docker Compose
      shell: bash
      run: |
        DOCKER_COMPOSE_VERSION=$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4)
        sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Verify Docker Compose Installation
      shell: bash
      run: docker-compose --version

    - name: Build Docker Image
      shell: bash
      env:
        ECR_REMOTE_HOST: ${{ inputs.aws_ecr_repository }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ECR_SERVICE_NAME: ${{ inputs.docker_compose_service }}
        ECR_IMAGE_TAG: ${{ inputs.docker_image_tag }}
      run: |
        docker-compose -f ./docker/docker-compose.yml build ${{ inputs.docker_compose_service }}

    - name: Push Docker Image to ECR
      shell: bash
      env:
        ECR_REMOTE_HOST: ${{ inputs.aws_ecr_repository }}
        GITHUB_TOKEN: ${{ inputs.github_token }}
        ECR_SERVICE_NAME: ${{ inputs.docker_compose_service }}
        ECR_IMAGE_TAG: ${{ inputs.docker_image_tag }}
      run: |
        docker-compose -f ./docker/docker-compose.yml push ${{ inputs.docker_compose_service }}
