export const StackScreens = {
  ConcertStackScreen: 'ConcertStackScreen',
  FundingStackScreen: 'FundingStackScreen',
  ContentsStackScreen: 'ContentsStackScreen',
  CommunityStackScreen: 'CommunityStackScreen',
  MyStackScreen: 'MyStackScreen',
  LoginStackScreen: 'LoginStackScreen',
  CalendarStackScreen: 'CalendarStackScreen',
  ConcertSearchStackScreen: 'ConcertSearchStackScreen',
  HomeStackScreen: 'HomeStackScreen',
  SearchStackScreen: 'SearchStackScreen',
  SubscribedStackScreen: 'SubscribedStackScreen',
  VenueStackScreen: 'VenueStackScreen',
  ArtistStackScreen: 'ArtistStackScreen',
} as const
export const TabScreens = {
  MainTabScreen: 'MainTabScreen',
} as const
export const Screens = {
  ConcertMainScreen: 'ConcertMainScreen',
  ConcertDetailScreen: 'ConcertDetailScreen',
  ConcertListByCategoryScreen: 'ConcertListByCategoryScreen',
  ConcertTicketListScreen: 'ConcertTicketListScreen',
  MyScreen: 'MyScreen',
  LoginSelectionScreen: 'LoginSelectionScreen',
  EmailSignupScreen: 'EmailSignupScreen',
  EmailLoginScreen: 'EmailLoginScreen',
  EmailConfirmScreen: 'EmailConfirmScreen',
  FundingMainScreen: 'FundingMainScreen',
  CalendarMainScreen: 'CalendarMainScreen',
  ConcertSearchMainScreen: 'ConcertSearchMainScreen',
  ArtistAddScreen: 'ArtistAddScreen',
  HomeScreen: 'HomeScreen',
  LocationSelectionScreen: 'LocationSelectionScreen',
  SearchScreen: 'SearchScreen',
  SubscribedConcertListScreen: 'SubscribedConcertListScreen',
  VenueDetailScreen: 'VenueDetailScreen',
  ActivateUserConfirmScreen: 'ActivateUserConfirmScreen',
  ArtistDetailScreen: 'ArtistDetailScreen',
} as const
