FROM node:20.16.0-alpine AS builder
WORKDIR /surfers-root
ARG GITHUB_TOKEN
ENV GITHUB_TOKEN=${GITHUB_TOKEN}

RUN corepack enable

COPY package.json ./package.json
COPY yarn.lock ./yarn.lock
COPY .yarnrc.yml ./.yarnrc.yml
COPY ./tsconfig.base.json ./tsconfig.base.json
COPY ./packages ./packages
COPY ./apps/blog-client ./apps/blog-client

WORKDIR /surfers-root/apps/blog-client
RUN yarn install
RUN yarn workspace @coldsurfers/blog-client build

EXPOSE 4000
CMD ["yarn", "start"]
