version: '3.8'

services:
  coldsurf-io:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.coldsurf-io
      args:
        GITHUB_TOKEN: '${GITHUB_TOKEN}'
        PORT: 4001
    image: '${ECR_REMOTE_HOST}/coldsurf/coldsurf-io:latest'
    env_file:
      - ../apps/coldsurf-io/.env
    ports:
      - '4001:4001'
  blog-client:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.blog-client
      args:
        GITHUB_TOKEN: '${GITHUB_TOKEN}'
        PORT: 4000
    image: '${ECR_REMOTE_HOST}/coldsurf/blog-client:latest'
    env_file:
      - ../apps/blog-client/.env
    ports:
      - '4000:4000'
  wamuseum-client:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.wamuseum-client
      args:
        GITHUB_TOKEN: '${GITHUB_TOKEN}'
        PORT: 4002
    image: '${ECR_REMOTE_HOST}/coldsurf/wamuseum-client:latest'
    env_file:
      - ../apps/wamuseum-client/.env
    ports:
      - '4002:4002'
  billets-server:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.billets-server
      args:
        GITHUB_TOKEN: '${GITHUB_TOKEN}'
        PORT: 3001
    image: '${ECR_REMOTE_HOST}/coldsurf/billets-server:latest'
    env_file:
      - ../apps/billets-server/.env
    ports:
      - '3001:3001'
  wamuseum-server:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.wamuseum-server
      args:
        GITHUB_TOKEN: '${GITHUB_TOKEN}'
        PORT: 3002
    image: '${ECR_REMOTE_HOST}/coldsurf/wamuseum-server:latest'
    env_file:
      - ../apps/wamuseum-server/.env
    ports:
      - '3002:3002'
    # restart: unless-stopped
  # coldsurf-io-nginx:
  #   platform: linux/amd64
  #   build:
  #     context: ../
  #     dockerfile: ./docker/Dockerfile.nginx
  #     args:
  #       GITHUB_TOKEN: '${GITHUB_TOKEN}'
  #   image: '${ECR_REMOTE_HOST}/coldsurf/coldsurf-io-nginx:latest'
  #   ports:
  #     - '4001:4001'
