version: '3.8'

services:
  coldsurf-io:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.coldsurf-io
      args:
        GITHUB_TOKEN: '${GITHUB_TOKEN}'
    image: '${ECR_REMOTE_HOST}/coldsurf/coldsurf-io:latest'
    env_file:
      - ../apps/coldsurf-io/.env
    ports:
      - '4001:4001'
    volumes:
      - ../apps/coldsurf-io:/surfers-root/apps/coldsurf-io
    restart: unless-stopped
  blog-client:
    platform: linux/amd64
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.blog-client
      args:
        GITHUB_TOKEN: '${GITHUB_TOKEN}'
    image: '${ECR_REMOTE_HOST}/coldsurf/blog-client:latest'
    env_file:
      - ../apps/blog-client/.env
    ports:
      - '4000:4000'
    restart: unless-stopped
