name: 'ECR login composite action'
description: 'AWS ECR login'
inputs:
  aws_access_key_id:
    description: 'AWS access key id'
    required: true
  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
    default: 'ap-northeast-2'
  aws_ecr_repository:
    description: 'AWS ecr repository address'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Log in to Amazon ECR
      shell: bash
      run: |
        aws configure set aws_access_key_id ${{ inputs.aws_access_key_id }}
        aws configure set aws_secret_access_key ${{ inputs.aws_secret_access_key }}
        aws configure set region ${{ inputs.aws_region }}
        aws ecr get-login-password --region ${{ inputs.aws_region }} | docker login --username AWS --password-stdin ${{ inputs.aws_ecr_repository }}
