name: 'SST Next.js template action'
description: 'SST Next.js template'
inputs:
  aws_access_key_id:
    description: 'AWS access key id'
    required: true
  aws_secret_access_key:
    description: 'AWS secret access key'
    required: true
  aws_region:
    description: 'AWS region'
    required: true
    default: 'ap-northeast-2'
  work_dir:
    description: 'working directory'
    required: true

runs:
  using: 'composite'
  steps:
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '20.16.0'

    - name: corepack enable
      run: corepack enable

    - name: setup yarnrc
      run: |
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV

    - name: install dependencies
      run: yarn install

    - name: sst deploy
      working-directory: ${{ inputs.work_dir }}
      run: npx sst deploy --stage production
