ENV["NO_FLIPPER"] = "1"
ENV["RCT_NEW_ARCH_ENABLED"] = "1"

# Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

# react-native-permissions
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Use it to require both react-native's and this package's scripts:
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

#platform :ios, min_ios_version_supported
# react-native-code-push min version is 15.5
# https://github.com/microsoft/react-native-code-push/blob/master/CodePush.podspec#L13
platform :ios, '15.5'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true
$RNGoogleMobileAdsAsStaticFramework = true

target 'FstvlLifeApp' do
  config = use_native_modules!

  pod 'Firebase', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true

  pod 'react-native-config', :path => '../../../node_modules/react-native-config'

  # For extensions without React dependencies
  pod 'react-native-config/Extension', :path => '../../../node_modules/react-native-config'

  rn_maps_path = '../../../node_modules/react-native-maps'

  pod 'react-native-maps/Google', :path => rn_maps_path

  ENVFILES = {
    'Debug' => '$(PODS_ROOT)/../../.env.development',
    'Staging' => '$(PODS_ROOT)/../../.env.staging',
    'Release' => '$(PODS_ROOT)/../../.env.production',
  }

  # react-native-permissions
  setup_permissions([
    # 'AppTrackingTransparency',
    # 'Bluetooth',
    # 'Calendars',
    # 'CalendarsWriteOnly',
    # 'Camera',
    # 'Contacts',
    # 'FaceID',
    'LocationAccuracy',
    'LocationAlways',
    'LocationWhenInUse',
    # 'MediaLibrary',
    # 'Microphone',
    # 'Motion',
    # 'Notifications',
    # 'PhotoLibrary',
    # 'PhotoLibraryAddOnly',
    # 'Reminders',
    # 'Siri',
    # 'SpeechRecognition',
    # 'StoreKit',
  ])

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#  use_flipper!()

  # RN Maps patch start
  # https://github.com/react-native-maps/react-native-maps/issues/5467
  # sudo chown -R $(whoami) ios
  # sudo chmod -R u+rw ios
  # Replace @import GoogleMaps; with #import <GoogleMaps/GoogleMaps.h> in specific files
  specific_files = [
    "#{Pod::Config.instance.installation_root}/Pods/Google-Maps-iOS-Utils/Sources/GoogleMapsUtilsObjC/include/GMSMarker+GMUClusteritem.h",
    "#{Pod::Config.instance.installation_root}/Pods/Google-Maps-iOS-Utils/Sources/GoogleMapsUtilsObjC/include/GMUGeoJSONParser.h",
    "#{Pod::Config.instance.installation_root}/Pods/Google-Maps-iOS-Utils/Sources/GoogleMapsUtilsObjC/include/GMUPolygon.h",
    "#{Pod::Config.instance.installation_root}/Pods/Google-Maps-iOS-Utils/Sources/GoogleMapsUtilsObjC/include/GMUWeightedLatLng.h",
    "#{Pod::Config.instance.installation_root}/Pods/GoogleMaps/Maps/Sources/GMSEmpty.h"
  ]

  specific_files.each do |file|
    if File.exist?(file)
      text = File.read(file)
      if text.include?("@import GoogleMaps;")
        new_text = text.gsub("@import GoogleMaps;", "#import <GoogleMaps/GoogleMaps.h>")
        File.open(file, "w") { |f| f.write(new_text) }
        puts "🔧 Patched @import in: #{file}"
      else
        puts "ℹ️ No @import GoogleMaps; found in: #{file}"
      end
    else
      puts "⚠️ File not found: #{file}"
    end
  end
  # RN Maps patch end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
      end
    end

    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
