# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    releaseKeyStorePath = File.join(Dir.pwd, '..', 'app/release.keystore')
    gradle(
      task: "bundle",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => releaseKeyStorePath,
        "android.injected.signing.store.password" => ENV['release-key-store-store-password'],
        "android.injected.signing.key.alias" => ENV['release-key-store-alias'],
        "android.injected.signing.key.password" => ENV['release-key-store-key-password'],
      }
    )
    supply(
      package_name: ENV['package-name'],
      track: "internal",
      json_key: ENV['service-account-json-file'],
      aab: "./app/build/outputs/bundle/release/app-release.aab",
      timeout: 1200,
      skip_upload_apk: true,
      release_status: "draft"
    )
    # gradle(task: "clean assembleRelease")

    # upload_to_play_store(track: "beta")
    # crashlytics

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
