export const INFINITE_HOME_COLLECTION_ITEM_WIDTH_PERCENT = {
  DEFAULT: 12,
  X_LARGE: 15,
  LARGE: 24,
};

export const INFINITE_HOME_COLLECTION_PER_PAGE_ITEM_COUNT = {
  DEFAULT: 8,
  X_LARGE: 6,
  LARGE: 3,
};
