export const APP_CONTAINER_MAX_WIDTH = 1440;
export const APP_CONTAINER_PADDING = 80;
export const APP_CONTAINER_PADDING_LARGE = 20;
export const SLICK_SLIDE_INTER_SPACE = 16;
export const SLICK_SLIDE_INTER_SPACE_LARGE = 8;

export const HOME_COLLECTION_COL_DEFAULT = 4;
export const HOME_COLLECTION_COL_SMALL = 2;
