export const APP_CONTAINER_MAX_WIDTH = 1440;
export const APP_CONTAINER_PADDING = 40;
export const APP_CONTAINER_PADDING_LARGE = 20;
export const SLICK_SLIDE_INTER_SPACE = 16;
export const SLICK_SLIDE_INTER_SPACE_LARGE = 8;
