name: SurfTree Web CI/CD Pipeline

on:
  workflow_dispatch: # Allows the workflow to be triggered manually
  # push:
    # tags: # Trigger on push to a tag
      # - 'v*-surf-tree-web' # Adjust pattern as needed (e.g., v1.0.0)
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to AWS
        uses: ./.github/workflows/composites/aws-login
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Create .env file from template
        working-directory: ./apps/surf-tree
        run: |
          echo "SURF_TREE_DOMAIN_CERT_ARN=${{ secrets.SURF_TREE_DOMAIN_CERT_ARN }}" >> .env
          echo "SURF_TREE_DOMAIN_NAME=${{ secrets.SURF_TREE_DOMAIN_NAME }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.SURF_TREE_FIREBASE_API_KEY }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.SURF_TREE_FIREBASE_AUTH_DOMAIN }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.SURF_TREE_FIREBASE_PROJECT_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.SURF_TREE_FIREBASE_STORAGE_BUCKET }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.SURF_TREE_FIREBASE_MESSAGING_SENDER_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.SURF_TREE_FIREBASE_APP_ID }}" >> .env
          echo "NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID=${{ secrets.SURF_TREE_FIREBASE_MEASUREMENT_ID }}" >> .env

      - name: SST Next.js template action
        uses: ./.github/workflows/composites/sst-nextjs-template
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          work_dir: ./apps/surf-tree
          github_token: ${{ secrets.GITHUB_TOKEN }}
