name: Blog Client CI/CD Pipeline

on:
  workflow_dispatch: # Allows the workflow to be triggered manually
  push:
    tags: # Trigger on push to a tag
      - 'v*-blog-client' # Adjust pattern as needed (e.g., v1.0.0)
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: ./.github/workflows/composites/ecr-login
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_ecr_repository: ${{ secrets.ECR_REPOSITORY }}

      - name: Get the tag name
        id: get_tag
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV

      - name: Create .env file from template
        run: |
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> ./apps/blog-client/.env
          echo "NOTION_BLOG_DATABASE_ID=${{ secrets.NOTION_BLOG_DATABASE_ID }}" >> ./apps/blog-client/.env
          echo "NOTION_RESUME_DATABASE_ID=${{ secrets.NOTION_RESUME_DATABASE_ID }}" >> ./apps/blog-client/.env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> ./apps/blog-client/.env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> ./apps/blog-client/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./apps/blog-client/.env
          echo "NOTION_AUTH_TOKEN=${{ secrets.NOTION_AUTH_TOKEN }}" >> ./apps/blog-client/.env
          echo "NOTION_ACTIVE_USER=${{ secrets.NOTION_ACTIVE_USER }}" >> ./apps/blog-client/.env
          echo "NOTION_FILE_TOKEN=${{ secrets.NOTION_FILE_TOKEN }}" >> ./apps/blog-client/.env
          touch "./apps/billets-web/.env"
          touch "./apps/wamuseum-client/.env"
          touch "./apps/billets-server/.env"
          touch "./apps/wamuseum-server/.env"

      - name: Docker Compose build and push
        uses: ./.github/workflows/composites/docker-compose-build
        with:
          docker_compose_service: 'blog-client'
          aws_ecr_repository: ${{ secrets.ECR_REPOSITORY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          docker_image_tag: ${{ env.TAG_NAME }}

      - name: Update ECS
        uses: ./.github/workflows/composites/update-ecs-task-def-service
        with:
          aws_ecr_repository: ${{ secrets.ECR_REPOSITORY }}
          docker_image_name: 'blog-client'
          tag_name: ${{ env.TAG_NAME }}
          ecs_task_definition: ${{ secrets.ECS_TASK_DEFINITION }}
          ecs_service: 'blog-client'
          ecs_cluster: ${{ secrets.ECS_CLUSTER }}
          ecs_container_definition_index: 2
