name: Billets Server CI/CD Pipeline

on:
  workflow_dispatch: # Allows the workflow to be triggered manually

jobs:
  blog_client_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Amazon ECR
        uses: ./.github/workflows/composites/ecr-login
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_ecr_repository: ${{ secrets.ECR_REPOSITORY }}

      - name: Create .env file from template
        run: |
          echo "BILLETS_APP_APPLE_BUNDLE_ID=${{ secrets.BILLETS_APP_APPLE_BUNDLE_ID }}" >> ./apps/billets-server/.env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./apps/billets-server/.env
          echo "GOOGLE_OAUTH_CLIENT_ID=${{ secrets.GOOGLE_OAUTH_CLIENT_ID }}" >> ./apps/billets-server/.env
          echo "BILLETS_SERVER_JWT_SECRET=${{ secrets.BILLETS_SERVER_JWT_SECRET }}" >> ./apps/billets-server/.env
          echo "BILLETS_SERVER_MAILER_EMAIL_ADDRESS=${{ secrets.BILLETS_SERVER_MAILER_EMAIL_ADDRESS }}" >> ./apps/billets-server/.env
          echo "BILLETS_SERVER_MAILER_EMAIL_APP_PASSWORD=${{ secrets.BILLETS_SERVER_MAILER_EMAIL_APP_PASSWORD }}" >> ./apps/billets-server/.env
          echo "BILLETS_SERVER_MAILER_SERVICE=${{ secrets.BILLETS_SERVER_MAILER_SERVICE }}" >> ./apps/billets-server/.env
          touch "./apps/coldsurf-io/.env"
          touch "./apps/blog-client/.env"
          touch "./apps/wamuseum-client/.env"
          touch "./apps/wamuseum-server/.env"

      - name: Docker Compose build and push
        uses: ./.github/workflows/composites/docker-compose-build
        with:
          docker_compose_service: 'billets-server'
          aws_ecr_repository: ${{ secrets.ECR_REPOSITORY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Terraform apply
        uses: ./.github/workflows/composites/terraform-apply
        with:
          working_directory: ./terraform/
          aws_security_group_id: ${{ secrets.AWS_SECURITY_GROUP_ID }}

      - name: SSH ec2 and run cli
        uses: ./.github/workflows/composites/ssh-ec2-cli
        with:
          ec2_pem_key: ${{ secrets.EC2_PEM_KEY }}
          ec2_host: ${{ secrets.EC2_HOST }}
          ec2_user: ${{ secrets.EC2_USER }}
          ecr_repository: ${{ secrets.ECR_REPOSITORY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          aws_region: ${{ secrets.AWS_REGION }}
          docker_compose_service: 'billets-server'
