name: Wamuseum Client CI/CD Pipeline

on:
  workflow_dispatch: # Allows the workflow to be triggered manually
  # push:
    # tags: # Trigger on push to a tag
      # - 'v*-wamuseum-client' # Adjust pattern as needed (e.g., v1.0.0)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to AWS
        uses: ./.github/workflows/composites/aws-login
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Create .env file from template
        working-directory: ./apps/wamuseum-client
        run: |
          echo "NEXT_PUBLIC_WAMUSEUM_S3_BUCKET_URL=${{ secrets.NEXT_PUBLIC_WAMUSEUM_S3_BUCKET_URL }}" >> .env
          echo "WAMUSEUM_CLIENT_DOMAIN_NAME=${{ secrets.WAMUSEUM_CLIENT_DOMAIN_NAME }}" >> .env
          echo "WAMUSEUM_CLIENT_DOMAIN_CERT_ARN=${{ secrets.WAMUSEUM_CLIENT_DOMAIN_CERT_ARN }}" >> .env

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: corepack enable
        run: |
          corepack enable
          COREPACK_INTEGRITY_KEYS=0 corepack prepare --activate

      - name: setup yarnrc
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV

      - name: install dependencies
        run: pnpm install
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: sst deploy
        working-directory: ./apps/wamuseum-client
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx sst deploy --stage production
