name: Blog Client CI/CD Pipeline

on:
  workflow_dispatch: # Allows the workflow to be triggered manually
  push:
    tags: # Trigger on push to a tag
      - 'v*-blog-client' # Adjust pattern as needed (e.g., v1.0.0)
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to AWS
        uses: ./.github/workflows/composites/aws-login
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}

      - name: Create .env file from template
        working-directory: ./apps/blog-client
        run: |
          echo "NOTION_TOKEN=${{ secrets.NOTION_TOKEN }}" >> .env
          echo "NOTION_BLOG_DATABASE_ID=${{ secrets.NOTION_BLOG_DATABASE_ID }}" >> .env
          echo "NOTION_RESUME_DATABASE_ID=${{ secrets.NOTION_RESUME_DATABASE_ID }}" >> .env
          echo "CLOUDINARY_API_KEY=${{ secrets.CLOUDINARY_API_KEY }}" >> .env
          echo "CLOUDINARY_API_SECRET=${{ secrets.CLOUDINARY_API_SECRET }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "NOTION_AUTH_TOKEN=${{ secrets.NOTION_AUTH_TOKEN }}" >> .env
          echo "NOTION_ACTIVE_USER=${{ secrets.NOTION_ACTIVE_USER }}" >> .env
          echo "NOTION_FILE_TOKEN=${{ secrets.NOTION_FILE_TOKEN }}" >> .env
          echo "BLOG_CLIENT_DOMAIN_NAME=${{ secrets.BLOG_CLIENT_DOMAIN_NAME }}" >> .env
          echo "BLOG_CLIENT_DOMAIN_CERT_ARN=${{ secrets.BLOG_CLIENT_DOMAIN_CERT_ARN }}" >> .env

      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: '20.16.0'

      - name: corepack enable
        run: corepack enable

      - name: setup yarnrc
        run: |
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          echo "GITHUB_TOKEN=$GITHUB_TOKEN" >> $GITHUB_ENV

      - name: install dependencies
        run: yarn install

      - name: sst deploy
        working-directory: ./apps/blog-client
        run: npx sst deploy --stage production
