name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    if: github.repository == 'coldsurfers/surfers-root'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/workflows/composites/setup
        with:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint files
        run: pnpm lint

      - name: Typecheck files
        run: pnpm turbo check:type

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          title: 'chore: version packages'
          commit: 'chore: version packages'
          publish: echo 'publish'
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
